Add custom positions
AppDevNext/AndroidChart pull request #139
Opened 2023-08-09 18:43 UTC by papjul

First of all, I'm very thankful to you for keeping this library alive!

This pull request adds ability to have custom positions for lines and labels.

Custom position for labels was already written by someone else so I cherry-picked it, then I added support for grid lines to follow position of labels as well.

Here is an example of a chart with customized positions for X and Y axis where I customized labels to achieve what I wanted to do:

Precipitation forecast:
![image](https://github.com/AppDevNext/AndroidChart/assets/1449159/53660c40-e5d0-456c-9acc-011ae981c50f)

I'm very new to AndroidChart, so it needs a review from someone with better knowledge, although risk should be very low as this new feature is hidden behind an option that is disabled by default, so there should be no impact on existing graphs.

Thank you,

2023-08-10 05:16 UTC, hannesa2 requested changes
It would be super nice, when we can have an own demo, which demonstrate this new feature (optional) and much more nicer would be an Espresso test (more optional)

Please change at least the format. Thank you !

2023-08-10 05:16 UTC, hannesa2 commented on MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
> +    {
I try to keep format of code unique, so please use everywhere this
`public void setShowSpecificLabelPositions(boolean showSpecificLabelPositions) {`
instead of your C style
```
    public void setShowSpecificLabelPositions(boolean showSpecificLabelPositions)
    {
```

2023-08-10 05:29 UTC, papjul commented on MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
> +    {
It's not mine, it's from the commit I cherry-picked, I actually write like you ;) Will make the change.

2023-08-10 05:37 UTC, hannesa2 commented on MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
> +    {
Nice, there is an example as well https://github.com/PhilJay/MPAndroidChart/pull/2692/files#diff-093b19f9f05a3593050879403f9fac2f27bd452ea0fcc4107c2bb53c95694937
maybe we can grab this as well ? Ok, Espresso is on my side.
Just for your info, there are already test results in job summary 
![image](https://github.com/AppDevNext/AndroidChart/assets/3314607/e5db8f39-332f-4d59-bfd2-b404b6d6a7e4)

But screenshot compare tests are currently impossible, because for tests there are random values https://github.com/AppDevNext/AndroidChart/pull/77

2023-08-13 07:15 UTC, papjul commented
I added the demo, I’m not sure what the numbers mean for activity listing, I had to shift numbers for other activities or it would crash on opening app. Please review if there is any impact.

I shortened "specificLabelPositions" to "specificPositions" as it also includes lines in my version.

I wanted to change the "C style syntax" you mentioned but when looking at the surrounding code it’s how functions above are written. So I would suggest making Java style homogenous with all functions on a separate work from this PR.

2023-08-13 08:28 UTC, hannesa2 commented
> I wanted to change the "C style syntax" you mentioned but when looking at the surrounding code it’s how functions above are written. So I would suggest making Java style homogenous with all functions on a separate work from this PR.

Agree, it's a general question if I should reformat all code and loose direct connect to upstream code.
* pro: a good baseline, for general improvements
* con: if upstream reactive again, all my changes will be pointless, because most developers use upstream

2023-08-13 12:44 UTC, hannesa2 commented
I see this is new sample nr. 23
![image](https://github.com/AppDevNext/AndroidChart/assets/3314607/f8cb85f9-9a10-497f-8b16-1b5aeb972599)


Unfortunately it doesn't extend sample nr. 1
![image](https://github.com/AppDevNext/AndroidChart/assets/3314607/59e396f1-5be2-4a9f-a09a-d02b0fdc90fa)

The best would be to extend sample 1 to show diff to sample 23 with same data. Or add an option in 1 to add custom positions.

But this is just optional.
Thanks for your afford !

2023-08-13 12:45 UTC, merged

2023-08-13 12:48 UTC, hannesa2 commented on MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/SpecificPositionsLineChartActivity.java
> +		leftAxis.setSpecificPositions(new float[]{0, 10, 20, 50, 100, 300});
Correct me if I'm wrong, this are the only significant two lines in this sample compared to sample1. Am I right ?

2023-08-13 13:05 UTC, papjul commented on MPChartExample/src/main/java/com/xxmassdeveloper/mpchartexample/SpecificPositionsLineChartActivity.java
> +		leftAxis.setSpecificPositions(new float[]{0, 10, 20, 50, 100, 300});
I didn't write this sample, but probably yes.

When the initial pull request was suggested, upstream asked to make it an option on an existing sample, instead of have a dedicated sample. As you suggested me to get this sample, I just copied/pasted it, fixed compilation errors due to code changes that happen in-between, but I didn’t analyze more than that.